---
{{- if eq .Values.tls.certSource "plaintext" }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: server-certificates
  namespace: {{ .Release.namespace }}
  labels: {{ include "server.labels" . | nindent 4 }}
stringData:
  tls.crt: |
    {{- .Values.tls.plaintext.certificate | nindent 4 }}
  tls.key: |
    {{- .Values.tls.plaintext.privateKey | nindent 4 }}
{{- end }}