apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.namespace }}
  name: ansibleforms-server-pv-claim
  labels:
    {{- include "server.labels" . | indent 4 }}
    {{- include "commonLables" . | indent 4 }}    
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi