{{ if eq .Values.mysql.credentials.source "plaintext"}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "databaseSecretName" .}}
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "commonLabels" . | indent 4 }}
stringData:
  db_password: {{ .Values.mysql.credentials.db_password }}
{{ end }}
---
{{- if eq .Values.tls.certSource "plaintext" }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "certificateSecretName" . }}
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "commonLabels" . | indent 4 }}  
stringData:
  tls.crt: |
    {{- .Values.tls.plaintext.certificate | nindent 4 }}
  tls.key: |
    {{- .Values.tls.plaintext.privateKey | nindent 4 }}
{{- end }}