{{ if eq .Values.mysql.credentials.source "plaintext"}}
---
apiVersion: v1
kind: Secret
metadata:
  name: ansibleforms-secrets
  namespace: {{ .Release.namespace }}
  labels:
    app.kubernetes.io/part-of: ansibleforms
stringData:
  db_user: {{ .Values.mysql.credentials.db_username }}
  db_password: {{ .Values.mysql.credentials.db_password }}
{{ end }}