apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: server
  labels:
    {{- include "server.labels" . | indent 4}}
spec:
  type: LoadBalancer
  ports:
    - name: "8443"
      port: 8445
      targetPort: 8443
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server
status:
  loadBalancer: {}
