apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: {{ .Values.namespace }}
  labels: {{ include "server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{ include "server.labels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ template "server.image" . }}
          name: server
          ports:
            - containerPort: 8443
          env:
            - name: PORT
              value: "8443"
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: HTTPS
              valueFrom:
                configMapKeyRef:
                  key: HTTPS
                  name: ansibleforms-env              
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ansibleforms-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ansibleforms-secrets
                  key: DB_PASSWORD
            - name: LOG_CONSOLE_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_CONSOLE_LEVEL
                  name: ansibleforms-env
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: ansibleforms-env
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.25"
              memory: 256Mi
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /app/dist/persistent
              name: server-persistent-storage
            - name: server-certificates
              mountPath: /app/dist/persistent/certificates/
      restartPolicy: Always
      volumes:
        - name: server-persistent-storage
          persistentVolumeClaim:
            claimName: ansibleforms-server-pv-claim
        - name: server-certificates
          secret:
            secretName: server-certificates