## TODO add custom CA of trust
## TODO add ingress
## TODO add resources requests & limits
## TODO change server certificates to secret + DB info
## TODO - add replicas? scalable?
## TODO think about labels. static?
## Validation for strings (such as expose.type)
namespace: ansibleforms

server:
  image: 
    repository: ansibleguy/ansibleforms
    tag: 5.0.1
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: ansibleforms
  port: 8443

# App must work with an SQL database
mysql:
  image:
    repository: mysql
    tag: "5.7"
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ansibleforms
  # To change them - convert the new creds to base64 E.g: echo -n 'myuser' | base64
  db_username: cm9vdA== #(root)
  db_password: QW5zaWJsZUZvcm1zITEyMw== # AnsibleForms!123
  # 
  existingSecret: asas

expose:
  # Choose the service type to expose the application. Options are:
  # 1) "ingress" - for external tls access. requires ingress controller
  #     configured on your cluster.
  # 2) "loadBalancer" - an external LoadBalancer. has to be available in your 
  #     infrestructure provider.
  # 3) "nodePort" - external access using the machine's port. least recommended
  #      method, use it only if all of the other are not available
  # You can read about the differnt services types to match your needs the best
  # https://platform9.com/blog/understanding-kubernetes-loadbalancer-vs-nodeport-vs-ingress/
  type: ingress
  loadBalancer: 
    port:
  hostname: ansibleforms.apps.ocp410-dev.cloudlet-dev.com

tls:
  # Enable or disable HTTPS to the application. Must be true of false - boolean
  enable: true
  # The source of the server certificate for TLS connections.
  # Can be either "secret", "plaintext"
  certSource: plaintext
  # The name of the secret, if using secret. keys must be:
  # "cert.pem" - the certificate
  # "key.pem" - the private key
  # Content must be in pem format
  # secretName: ""
  plaintext:
    # Your certificate data. should be in base64 or pem format.
    certificate: |

    # Private key of your certificate
    privateKey: | 

## General configurations for app costumization
## Uncomment wanted values

# # Nodejs environment. can be either "production" or "development"
environment: production
# Enable or disable the internal designer. Not reccommended, best practice is to take your forms from SCM
enableDesigner: true 
# Logging level. Options are "error", "warn", "notice", "info" and "debug"
logLevel: info
consoleLogLevel: debug
# # Name of mysql database
mysqlDatabase: AnsibleForms
baseURL: "/"