apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.namespace }}
  name: mysql
  labels: {{ include "mysql.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{ include "mysql.labels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ template "mysql.image" . }}
          name: mysql
          args:
            - "--ignore-db-dir=lost+found" # To avoid a common error with mysql 5.7 and k8s
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ansibleforms-secrets
                  key: db_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: ansibleforms-env
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.25"
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
            - name: mysql-my-cnf
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
      restartPolicy: Always
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ansibleforms-mysql-pv-claim
        - name: mysql-my-cnf
          configMap:
            name: mysql-my-cnf
            items:
            - key: my.cnf
              path: my.cnf
