apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.namespace }}
  name: ansibleforms-mysql-pv-claim
  labels: {{ include "mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
