---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: mysql
  labels: {{ include "mysql.labels" . | nindent 4 }}
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: mysql