---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.namespace }}
  name: mysql
  labels:
    {{- include "mysql.labels" . | indent 4 }}
    {{- include "commonLabels" . | indent 4 }}  
spec:
  ports:
    - name: db
      port: 3306
      targetPort: 3306
  selector:
    {{- include "mysql.labels" . | indent 4 }}